#! /bin/bash

if [ $# -lt 2 ]; then
echo "$0:
Geef een input formaat en een ouput formaat"

exit
fi

if (([ $1 == "wav" ] || [ $1 == "aif" ] || [ $1 == "flac" ]) &&
    ([ $2 == "wav" ] || [ $2 == "aif" ] || [ $2 == "flac" ]))
then

DirName=${PWD##*/}
InExt=$1
OutExt=$2
NewDir="${DirName}${OutExt}"

mkdir "${NewDir}"


for f in *.${InExt}; do
echo "${f}"
ffmpeg -i "${f}" "`basename "${f}" .$InExt`.$OutExt"
mv "`basename "${f}" .$InExt`.$OutExt" "${NewDir}"

done

else
	echo "this file is not supported"

fi
