#! /bin/bash
#knipt audio file in het door te gebruiker aan te geven gelijke delen


if [ $# -lt 3 ]; then
echo "$0:
Geef een filepath
(bij spaties als volgt 
"~/user/audio file/file.wav" 
dus geen backslash bij spatie!)

het aantal slices en de extensie(geen mp3)"
exit
fi

FileName="$1"
Slices=$2
Ext=$3
lengte=`soxi -s "${FileName}"`
blocksize=`echo $lengte / $Slices | bc`
pt2=0 
pt3=`echo $pt2 + $blocksize | bc`

echo soxi "${FileName}" $Ext
sleep 3

for ((pt2 = 0; $pt2 < $lengte; pt2 =`echo $pt2+$blocksize | bc` ))
do 
	sox "${FileName}" "${FileName}"${pt2}${Ext} trim ${pt2}s ${blocksize}s
done


echo "Sliced succesvol!"

#Pjotr Lasschuit
