
all: hallo oppervlakte plus arrays grootstegetal

hallo: 1stfunctie.o
	g++ -o hallo 1stfunctie.o

.cpp.o:
	g++ -c $<

oppervlakte: oppervlakte.o
	g++ -o oppervlakte oppervlakte.o

.cpp.o:
	g++ -c $<

plus: plus.o
	g++ -o plus plus.o

.cpp.o:
	g++ -c $<

arrays: arrays.o
	g++ -o arrays arrays.o
.cpp.o:
	g++ -c $<

grootstegetal: grootstegetal.o
	g++ -o grootstegetal grootstegetal.o
.cpp.o:
	g++ -c $<
clean:
	rm -f *.o
	

